---
- hosts: all
  tasks:
    - name: Modify  Query_Cache_Size
      lineinfile:
        state: present
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        line: "query_cache_size = 32M"
        regexp: '^(#)?.*query_cache_size.*=.*$'
    - name: Modify  Max_Allowed_Packet
      lineinfile:
        state: present
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        line: "max_allowed_packet = 64M"
        regexp: '^(#)?.*max_allowed_packet.*=.*$'
    - name: Modify  innodb_log_file_size
      lineinfile:
        state: present
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        line: "innodb_log_file_size = 256M"
        regexp: '^(#)?.*innodb_log_file_size.*=.*$'

    - name: Restart MySQL / MariaDB server
      service:
        name: mariadb
        state: restarted

    - name: Add OTRS Database
      mysql_db:
        state: present
        name: "{{ OTRS_DB }}"
        encoding: utf8
        login_user: "root"
        login_unix_socket: "/run/mysqld/mysqld.sock"

    - name: Add OTRS User and privileges
      mysql_user:
        state: present
        name: "{{ OTRS_DB_USER }}"
        password: "{{ OTRS_DB_PASS }}"
        priv: "{{ OTRS_DB}}.*:all"
        login_unix_socket: "/run/mysqld/mysqld.sock"
        login_user: "root"

