---
- hosts: all

  tasks:
    - apt:
        state: present
        name:
          - aptitude
          - cpanminus
        force_apt_get: yes

    # - name: Add Certbot repo
    #   apt_repository:
    #     state: present
    #     repo: "ppa:certbot/certbot"
    #     filename: certbot-ppa

    # - name: Install Certbot
    #   apt:
    #     state: present
    #     name:
    #       - python-certbot-apache

    - name: Update & Upgrade packages
      apt:
        update_cache: yes
        name: '*'
        state: latest

    - name: Install OTRS requirements
      apt:
        name:
          - apache2
          - mariadb-server
          - mariadb-client
          - mariadb-backup
          - libapache2-mod-perl2
          - libdbd-mysql-perl
          - libtimedate-perl
          - libnet-dns-perl
          - libnet-ldap-perl
          - libio-socket-ssl-perl
          - libpdf-api2-perl
          - libdbd-mysql-perl
          - libsoap-lite-perl
          - libtext-csv-xs-perl
          - libjson-xs-perl
          - libapache-dbi-perl
          - libxml-libxml-perl
          - libxml-libxslt-perl
          - libyaml-perl
          - libarchive-zip-perl
          - libcrypt-eksblowfish-perl
          - libencode-hanextra-perl
          - libmail-imapclient-perl
          - libtemplate-perl
          - libauthen-ntlm-perl
          - libdatetime-perl
        state: present

    - name: Install CPAN Modules
      cpanm:
        name: "{{ item }}"
        system_lib: yes
      with_items:
        - "DateTime::TimeZone"
